### ISSUE TITLE
TransbankApi - Captura Diferida

### ISSUE THREAD

**Issue by CaroRed** [DarkGhostHunter/TransbankApi#14]
Hola estoy probando webpay con captura diferida que es lo que necesita un cliente y sale este error en capture.php:
Fatal error: Uncaught SoapFault:  in D:\www\2020\06\transbank-api\vendor\darkghosthunter\transbank-api\src\Clients\Webpay\PlusCapture.php:59 Stack trace: #0 D:\www\2020\06\transbank-api\vendor\darkghosthunter\transbank-api\src\Clients\Webpay\PlusCapture.php(59): SoapClient->__call('capture', Array) #1 D:\www\2020\06\transbank-api\vendor\darkghosthunter\transbank-api\src\Clients\Webpay\PlusCapture.php(38): DarkGhostHunter\TransbankApi\Clients\Webpay\PlusCapture->performCapture(Object(stdClass)) #2 D:\www\2020\06\transbank-api\vendor\darkghosthunter\transbank-api\src\Adapters\WebpayAdapter.php(160): DarkGhostHunter\TransbankApi\Clients\Webpay\PlusCapture->capture(Object(DarkGhostHunter\TransbankApi\Transactions\WebpayTransaction)) #3 D:\www\2020\06\transbank-api\vendor\darkghosthunter\transbank-api\src\AbstractService.php(169): DarkGhostHunter\TransbankApi\Adapters\WebpayAdapter->commit(Object(DarkGhostHunter\TransbankApi\Transactions\WebpayTransaction)) #4 D:\www\2020\06\transbank-api\vendor in D:\www\2020\06\transbank-api\vendor\darkghosthunter\transbank-api\src\Adapters\WebpayAdapter.php on line 164

Estoy usando el ejemplo que sale en la página https://github.com/DarkGhostHunter/TransbankApi/blob/master/examples/webpay-defer-capture-nullify/capture.php

Lo estoy haciendo en mi localhost. El createDefer funciona y el código de return también, solo en capture.php se cae.

Les agradezco desde ya.

**Comment by DarkGhostHunter** [comment]
Es un error en la implementación SOAP. Si no es un problema de credenciales, no hay nada que pueda hacer. Seguramente algo cambió en el API de Transbank.

Le echaré un vistazo el fds.

**Comment by DarkGhostHunter** [comment]
Parece que era problema de Webpay, porque acabo de probar y no presenta problemas:

![image](https://user-images.githubusercontent.com/5141911/83994273-e1796400-a923-11ea-95cd-6549eb150a93.png)

Y hasta la anulé:

![image](https://user-images.githubusercontent.com/5141911/83994292-ee965300-a923-11ea-9f66-5d272c7b6a0a.png)

Esto en PHP 7.4.5.

Cerrando con el típico _irreproducible_

**Comment by CaroRed** [comment]
Gracias. Pero a mi me sigue dando error que versión del vendor usas?
Porque yo bajé la ultima con composer.
Tendra algo que ver?

Gracias.

**Comment by DarkGhostHunter** [comment]
Versión del Vendor? Las últimas.

**Comment by DarkGhostHunter** [comment]
Recontra actualizé. Sigue sin problemas. Check your env.

**Comment by CaroRed** [comment]
Gracias Italo, veré cual es el problema entonces.

Saludos.

**Comment by DarkGhostHunter** [comment]
Suerte.
