### ISSUE TITLE
publicKey

### ISSUE THREAD

**Issue by Nemonikko** [DarkGhostHunter/TransbankApi#7]
Hola que conversión debo usar para obtener la clave publica de la calve privada?

formato .pem .pub?

namespace App;

use DarkGhostHunter\TransbankApi\Transbank;

$transbank = Transbank::make('production', [
    'webpay' => [
        'commerceCode' => '5000000001',
        'publicKey' => 'ABCD1234EF...',
        'publicCert' => '---BEGIN CERTIFICATE---...'
    ],
]);

**Comment by DarkGhostHunter** [comment]
Las que proporciona tu programa favorito.
